# Generated by Django 4.0.6 on 2022-08-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_director_delete_artists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
