# Generated by Django 4.0.6 on 2022-08-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
